[package]
name = "mdbook-permalinks"
publish = true
version = "1.1.2"

edition.workspace = true
rust-version.workspace = true

authors.workspace = true
license.workspace = true
repository.workspace = true

# categories = ["command-line-utilities"]
# description = "toolkit for mdBook ðŸ“–"
# documentation = "https://tonywu6.github.io/mdbookkit/"
# keywords = ["mdbook", "documentation", "rust-analyzer", "lsp", "permalink"]
# readme = "README.md"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
console = { workspace = true }
git2 = { version = "0.20.1", default-features = false }
gix-url = { version = "0.30.0" }
log = { workspace = true }
mdbook = { workspace = true }
mdbookkit = { workspace = true }
miette = { workspace = true }
percent-encoding = { version = "2.3.1" }
pulldown-cmark = { workspace = true }
serde = { workspace = true }
tap = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true, features = ["serde"] }

[dev-dependencies]
assert_cmd = { workspace = true }
insta = { workspace = true }
mdbookkit = { workspace = true, features = ["_testing"] }
predicates = { workspace = true }
rstest = { workspace = true }
tempfile = { workspace = true }
